### ISSUE TITLE
Existing $PROJ_FNAME$.custom_argvars does not get updated

### ISSUE THREAD

**Issue by ghost** [IARSystems/ewlaunch#1]
Hi,

I've run into a minor potential issue related to this nice tool.

__Description of the possible issue__
This issue affects EWlaunch v1.0.
If there is a project with a pre-existing `$PROJ_FNAME$.custom_argvars` file, EWlaunch is not touching it.
Then, when the EW version selection for the aforementioned project is performed, it does not become persistent across sessions.

__Suggested fix__
If the project already comes with the  `$PROJ_FNAME$.custom_argvars` __and__ has no EWlaunch information, append the necessary XML keys, in order to get persistence.

**Comment by antonf-iar** [comment]
The custom argument variable file is [workspace name].custom_argvars. That is also how IAR Embedded Workbench locates it.

If there is an existing file, it should be updated.

**Comment by ghost** [comment]
It is right. So that was the source of my confusion.  From the EWlaunch perspective, the custom argument variable files are directly associated to their respective workspace (`.eww`), not with the projects within. Thanks.
