### ISSUE TITLE
delete modules and variables that are not used in IAR 

### ISSUE THREAD

**Issue by Hoseinbme** [IARSystems/ewlaunch#5]
Hi im new to embedded system , I am using IAR compiler to work with ARM ST MCUS
        And I want to use CMSIS DSP library which is a big library
        The problem I faced is that when I use functions related to Fourier calculation, it gives an out of memory error while I used a small length for Fourier, but the compiler added the whole library to my project, There are notes that IAR stated that modules and variables that are not needed are not used.
        And after a lot of searching and asking, <https://github.com/ARM-software/CMSIS-DSP/issues/91>I found out that it is possible to define a series of rules for the compiler to use only the necessary parts that must be defined before the DSP library is compiled.

In the IAR compiler,  CMSIS  libraries are added with just one tick.
Now my question is, is it possible to add settings for this library?
And if possible, to which part should these commands be added, because iar has several options

project-->option-->compiler-->preprocess
project-->option-->compiler-->extra option -->command line
project-->option-->assembler-->preprocess
project-->option-->assembler-->extra option -->command line
project-->option-->linker-->define....
project-->option-->linker-->extra option -->command line
.
.
Is there a training video or ... available?

**Comment by antonf-iar** [comment]
Hi, support questions are handled by IAR technical support:
https://www.iar.com/knowledge/support/request-technical-support
